### ISSUE TITLE
[Bug] Game crashed

### ISSUE THREAD

**Issue by Aizelis** [UnlegitMinecraft/FDPClientChina#16]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
game crashed

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Launch game
2. Game crashed

**Expected behavior**
The game crashes the first time i start it up and doesn't even go to the main gui

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPCNClient-c1abea8.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 13/07/24 12:41
Description: Initializing game

java.lang.IllegalStateException: From thread Thread[Client thread,10,main]: Thread[Thread-8,10,main] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3189)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

 
```

**System Information**
 - OS: [Windows 10]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [FDPCNClient-c1abea8]

**Other Installed Mods**
Only FDPCN

**Additional info**
<Add any other context about the problem here.>

**Comment by laoshuikaixue** [comment]
It seems like the issue you're encountering might be related to your graphics card. The error suggests that there's a problem with the OpenGL context, which could be caused by outdated or incompatible graphics drivers.

**Steps to try:**

1. **Check and update your graphics card drivers**: Ensure that your graphics drivers are up-to-date. You can usually do this through the manufacturer's website or your system's update utility.
   
2. **Upgrade your graphics card**

3. **Use Lastest Version**
