### ISSUE TITLE
[Bug] Game Crashed

### ISSUE THREAD

**Issue by muwenyan521** [UnlegitMinecraft/FDPClientChina#17]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Game crashed

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Launch game
2. The game window appears
3. The progress bar goes all the way to the end.
4. Game crashed

**Expected behavior**
The game crashes the first time i start it up.

**Screenshots/Video**

https://github.com/user-attachments/assets/ae080e22-11d3-4399-8a20-1073c0d7d8d9

**Crash Report**
If your game crashed, please paste your crash report below.

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPCNClient-c1abea8.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 24-7-28 下午2:00
Description: Initializing game

java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-8,5,main] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.forceDestroy(ContextGL.java:241)
	at org.lwjgl.opengl.DrawableGL.destroy(DrawableGL.java:130)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:834)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.handler$startGame$zzg000(Minecraft.java:3191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:496)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_412, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 1114842008 bytes (1063 MB) / 2248146944 bytes (2144 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1843m -Xmx12288m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (FDPCNClient-c1abea8.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 555.99' Renderer: 'NVIDIA GeForce 940MX/PCIe/SSE2'
	Launched Version: 1.8.9-Forge_11.15.1.2318
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce 940MX/PCIe/SSE2 GL version 4.6.0 NVIDIA 555.99, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
```

**System Information**
 - OS: Windows 11
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 5.3.4

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Only FDPCN

**Additional info**
<Add any other context about the problem here.>

**Comment by laoshuikaixue** [comment]
Sorry, we refuse to use PCL launcher. Please use HMCL instead
